#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#!/usr/bin/env sh


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               3
yabai -m config left_padding                 3
yabai -m config right_padding                3
yabai -m config window_gap                   5

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app="Systemeinstellungen" manage=off
yabai -m rule --add title='Settings$' manage=off
# Hover Boxes
yabai -m rule --add app="^(JetBrains Toolbox|duet|1Password)$" manage=off
# Main Browser
yabai -m rule --add app="^(Firefox)$" space=1
# Coding Space
# yabai -m rule --add app="^(Code|RStudio|Neovide)$" space=2
# Test Browser
yabai -m rule --add app="^(Google Chrome)$" space=2
# Jetbrains apps
# apps="^(IntelliJ IDEA|WebStorm|RubyMine|PyCharm|DataGrip|CLion)$"
# yabai -m rule --add app="${apps}" manage=off
# Music
yabai -m rule --add app="^(Spotify|Amazon Music|Music)$" space=5
# Social
yabai -m rule --add app="^(Slack|WhatsApp|Microsoft Teams|Discord)$" space=6
# Remote
yabai -m rule --add app="^(Parsec|AnyDesk|Microsoft Remote Desktop)$" space=7 manage=off
yabai -m config external_bar all:0:25

echo "yabai configuration loaded.."
